# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.IntegerField(default=0)),
                ('personnel_id', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelBrowseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('personnel_id', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('browse_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id', models.IntegerField(default=0)),
                ('input_location', models.CharField(max_length=200)),
                ('input_user', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_location', models.CharField(max_length=200)),
                ('input_user', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.BooleanField(default=True)),
                ('ID_number', models.IntegerField(default=0)),
                ('is_own_house', models.BooleanField(default=False)),
                ('is_minimum_security', models.BooleanField(default=False)),
                ('family_members', models.IntegerField(default=0)),
                ('is_medical_security', models.BooleanField(default=False)),
                ('job_source', models.CharField(max_length=50)),
                ('annual_earnings', models.IntegerField(default=0)),
                ('is_corps', models.BooleanField(default=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('ID_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('is_three_personnel', models.BooleanField(default=False)),
                ('present_address', models.CharField(max_length=500)),
                ('passport_number', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=50)),
                ('educational_level', models.CharField(max_length=50)),
                ('political_face', models.CharField(max_length=50)),
                ('is_married', models.BooleanField(default=False)),
                ('health', models.CharField(max_length=500)),
            ],
        ),
    ]
