# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:56
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='personnel_id',
        ),
        migrations.RemoveField(
            model_name='personnelbrowselog',
            name='personnel_id',
        ),
        migrations.RemoveField(
            model_name='personnelmigration',
            name='personnel_id',
        ),
        migrations.AddField(
            model_name='family',
            name='personnel_uuid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelbrowselog',
            name='personnel_uuid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelmigration',
            name='personnel_uuid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='personnel_uuid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]

