# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170821_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_id',
        ),
        migrations.AddField(
            model_name='family',
            name='family_master_uuid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='family_relation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
