# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170821_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='note',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
