# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personnelprofile_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelprofile',
            old_name='input_user',
            new_name='input_user_id',
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='input_user_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='ID_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='ID_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='annual_earnings',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='family_members',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='job_source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='passport_number',
            field=models.CharField(max_length=255),
        ),
    ]
