# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170821_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelmigration',
            old_name='input_user',
            new_name='input_user_id',
        ),
        migrations.AddField(
            model_name='personnelmigration',
            name='input_user_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnelmigration',
            name='input_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='ID_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='annual_earnings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='input_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='input_user_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='job_source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
