# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170821_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelprofile',
            name='is_married',
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='marriage',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
