# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170821_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnelprofile',
            old_name='job_source',
            new_name='work_address',
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='work_desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='work_source',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
