# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170821_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='ID_photo',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
