# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_personnelprofile_id_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelprofile',
            name='ID_photo',
            field=models.CharField(default='', max_length=500),
        ),
    ]
