# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170822_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelprofile',
            name='input_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
