# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170822_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprofile',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='gender1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personnelprofile',
            name='is_minimum_security1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='is_corps',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='is_leader',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='is_medical_security',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnelprofile',
            name='is_three_personnel',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
